services:
  mongo:
    image: mongo:latest
    container_name: qbychat-mongo
    ports:
      - '27017:27017'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=password'
      - 'MONGO_INITDB_DATABASE=qbychat'
    volumes:
      - mongo:/data/db
    restart: no

  valkey:
    image: valkey/valkey:latest
    container_name: qbychat-valkey
    ports:
      - '6379:6379'
    restart: no

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: qbychat-zookeeper
    restart: no
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: qbychat-kafka
    hostname: kafka
    depends_on:
      - zookeeper
    restart: no
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    container_name: qbychat-schema-registry
    depends_on:
      - kafka
    restart: no
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081

#  kafka-ui:
#    container_name: qbychat-kafka-ui
#    image: provectuslabs/kafka-ui:latest
#    ports:
#      - "8086:8080"
#    depends_on:
#      - kafka
#    restart: no
#    environment:
#      KAFKA_CLUSTERS_NAME: local
#      KAFKA_CLUSTERS_BOOTSTRAPSERVERS: kafka:29092
#      KAFKA_CLUSTERS_SCHEMAREGISTRY: http://schema-registry:8081
#      DYNAMIC_CONFIG_ENABLED: 'true'

#  minio:
#    image: minio/minio:latest
#    container_name: qbychat-minio
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    volumes:
#      - minio:/data
#    restart: no
#    environment:
#      MINIO_ROOT_USER: root
#      MINIO_ROOT_PASSWORD: password
#    command: server /data --console-address ":9001"

volumes:
  mongo:
    driver: local
  minio:
    driver: local