spring:
  application:
    name: qbychat
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:password@localhost/qbychat?authSource=admin}
    redis:
      url: ${REDIS_URL:redis://127.0.0.1:6379/0}
  security:
    jwt:
      key: ${JWT_KEY:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
      expire: ${JWT_EXPIRE:1}

qbychat:
  websocket:
    path: /ws