spring:
  application:
    name: qbychat
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:password@localhost/qbychat?authSource=admin}
    redis:
      url: ${REDIS_URL:redis://127.0.0.1:6379/0}
  security:
    jwt:
      key: ${JWT_KEY:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
      expire: ${JWT_EXPIRE:3}
  cloud:
    stream:
      bindings:
        qbychatWebsocketPayloadConsumer-in-0:
          destination: qbychat-1
      kafka:
        bindings:
          supplier-out-0:
            producer:
              configuration:
                schema.registry.url: http://localhost:8081
                value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}

qbychat:
  websocket:
    path: /ws
  user:
    username:
      rule:
        regex: "^[a-zA-Z0-9_]+$"
        # General description of the rule
        description: "Username should only contain letters (a-z, A-Z), numbers (0-9), and underscores (_)."
