spring:
  application:
    name: qbychat
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:password@localhost/qbychat?authSource=admin}
    redis:
      url: ${REDIS_URL:redis://127.0.0.1:6379/0}
  security:
    jwt:
      key: ${JWT_KEY:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
      expire: ${JWT_EXPIRE:3}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      group-id: qbychat-brokers
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

qbychat:
  websocket:
    path: /ws
  user:
    username:
      rule:
        regex: "^[a-zA-Z0-9_]+$"
        # General description of the rule
        description: "Username should only contain letters (a-z, A-Z), numbers (0-9), and underscores (_)."
